global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # RT Predictor API metrics
  - job_name: 'rt-predictor-api'
    static_configs:
      - targets: ['rt-predictor-api:8181']
    metrics_path: '/metrics'

  # RT Predictor UI metrics (if enabled)
  - job_name: 'rt-predictor-ui'
    static_configs:
      - targets: ['rt-predictor-ui:9090']
    metrics_path: '/metrics'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
